Added Daily Quote feature
Canvasbird/canvasboard pull request #228
Opened 2020-12-04 11:19 UTC by DevoAbhi

## Issue that this pull request solves - There was no daily quote feature at the bottom of the dashboard page.

## Closes: #198

## Proposed changes - Adding a daily quote feature

### Brief description of what is fixed or changed - The dashboard page has now a daily quote present at the bottom of the page which gets updated every day.

## Types of changes - Feature added.

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

![canva-quote-desktop](https://user-images.githubusercontent.com/54373853/101157488-3803f880-3650-11eb-873a-67fc29c078cd.png)

![canva-quote-mobile](https://user-images.githubusercontent.com/54373853/101157527-43efba80-3650-11eb-9fcb-ec176fcbeb34.png)

## Other information

Please mention if any other changes are required in the PR.
Thank You.

2020-12-04 20:08 UTC, kingavatar commented on src/app/components/dashboard/dashboard.component.scss
> +
Don't Duplicate the class.
Add it below line no: 5

2020-12-04 20:44 UTC, goliakshay357 reviewed
![image](https://user-images.githubusercontent.com/32712438/101212844-6826b800-369f-11eb-8f75-b390d9ff8912.png)
Quote has to be in the bottom of the page. 
One silution would be:
1) Make container height to 100vh 
2) Place the quote div and container on the same DOM levels

2020-12-04 20:44 UTC, goliakshay357 commented on src/app/components/dashboard/dashboard.component.ts
> +    this.getQuote();
Please call this function inside NgonInit() of the component.

2020-12-09 15:23 UTC, DevoAbhi commented
Kindly review the latest commit.

2020-12-10 21:26 UTC, DevoAbhi commented
I have added some dummy quotes so that if the API fails to get a response, the user can still see a quote displayed.

2020-12-12 07:48 UTC, Kajol-Kumari requested changes
Hey @DevoAbhi I tested this PR and the quote is not appearing as expected. Maybe you should make it stick to the bottom by using something like below for the `quote` div.
```
position: fixed;
bottom: 8px;
```

Also please remove the commented codes if it's not required.

2020-12-14 07:32 UTC, Kajol-Kumari requested changes
Hey @DevoAbhi The feature is working fine. Justr address the minor requested changes and it will be good to go!

2020-12-14 07:32 UTC, Kajol-Kumari commented on src/app/components/dashboard/dashboard.component.ts
> +
Add the missing paranthesis(`}`) here. This is making your build fail

2020-12-14 07:32 UTC, Kajol-Kumari commented on src/app/components/dashboard/dashboard.component.html
> +  <!-- <input type="text" [(ngModel)]="folderName"> -->
If this comment line isn't required, please remove it.

2020-12-14 07:32 UTC, Kajol-Kumari commented on src/app/components/dashboard/dashboard.component.scss
> +      // cb-box-sizing: border-cb-box;
please remove the commented line

2020-12-14 19:02 UTC, Kajol-Kumari approved these changes
Thanks for incorporating all the request changes @DevoAbhi
LGTM 👍

2020-12-14 19:03 UTC, merged

2020-12-14 20:01 UTC, DevoAbhi commented
Thank you for merging my PR.
Thank you @Kajol-Kumari , @goliakshay357 and @kingavatar for reviewing my PR.