Long usernames overflow fixed
Canvasbird/canvasboard pull request #283
Opened 2020-12-23 04:18 UTC by OmarMorales71

## Issue that this pull request solves

 Closes: #271 

### Brief description of what is fixed or changed
When the username is very long it goes out of the box, only I added ellipsis to avoid overflow
## Types of changes

_Put an `x` in the boxes that apply_

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

![Screen Shot 2020-12-22 at 22 06 17](https://user-images.githubusercontent.com/66653667/102958700-266d7e00-44a3-11eb-8afe-3758ae72e242.png)

2020-12-23 11:52 UTC, Kajol-Kumari requested changes
Hey @OmarMorales71 Minor changes please incorporate the minor changes I requested. Along with that, Just a minor enhancement i.e user should be able to see his/her complete name after hovering on his/her user name on the workspace page.

2020-12-23 11:52 UTC, Kajol-Kumari commented on src/app/components/dashboard/dashboard.component.html
> +    <h3 style="color: black;
please define all the css in a class and just use that class here instead of inline styling.

2021-01-04 05:45 UTC, OmarMorales71 commented
@Kajol-Kumari sure! I'm working on it

2021-01-05 07:10 UTC, Kajol-Kumari approved these changes
@OmarMorales71 thanks for incorporating the suggested changes.
LGTM :+1:

2021-01-05 07:10 UTC, Kajol-Kumari commented on src/app/components/dashboard/dashboard.component.scss
> +}
leave a blank line at the end of the file

2021-01-07 07:30 UTC, merged