feat: Added GitHub action to auto-assign mentors
Canvasbird/canvasboard pull request #316
Opened 2021-01-04 09:11 UTC by m-code12

Fixes: #315

### What is the change?
Added a GitHub action to auto assign mentors for every pr.

### How was it tested?
I have tested the GitHub action in my personal repository. It automatically adds me as a reviewer on every pr created. Here is a link to the repo:
https://github.com/m-code12/Test_repo

## Submissions guide:

- [ ] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [ ] Have you lint your code locally prior to submission?

2021-01-05 07:47 UTC, Kajol-Kumari requested changes
@m-code12 please provide one blank line at the end of the each file

2021-01-05 08:31 UTC, m-code12 commented
> @m-code12 please provide one blank line at the end of the each file

Done

2021-01-07 07:24 UTC, Kajol-Kumari approved these changes

2021-01-07 07:25 UTC, merged

2021-01-07 07:30 UTC, Kajol-Kumari commented
Hey @m-code12 I have updated your score for this PR. If there is any PR or issue that I missed for giving score, please let me know :)